# fastlane/Fastfile
opt_out_usage
default_platform :ios

platform :ios do
  
  before_all do
    setup_circle_ci
    update_fastlane
  end
  
  error do |lane, exception|
    # You can log the error, send a notification, or take any other action
    UI.error("Error occurred during running the pipeline: #{exception.message}")
  end
  lane :run_all_unit_tests do
    run_tests(
      scheme: "brainwalletUnitTests",
      clean: true,
      code_coverage: true,
      configuration: "Debug",
      devices: ["iPhone 15 Pro Max"],
      output_types: "html,junit",
      output_directory: "./fastlane/test_output",
      skip_build: false
    )
  end
  lane :run_ui_iphone16promax_tests do
    run_tests(
      scheme: "brainwalletUITests",
      clean: true,
      code_coverage: true,
      configuration: "Debug",
      devices: ["iPhone 16 Pro Max"],
      output_types: "html,junit",
      output_directory: "./fastlane/test_output",
      skip_build: false
    )
  end
  lane :run_all_tests do
    run_tests(
      scheme: "brainwalletAllTests",
      clean: true,
      code_coverage: true,
      configuration: "Debug",
      devices: ["iPhone 15 Pro Max"],
      output_types: "html,junit",
      output_directory: "./fastlane/test_output",
      skip_build: false
    )
  end
  lane :run_ui_iphone13mini_tests do
    run_tests(
      scheme: "brainwalletAllTests",
      clean: true,
      code_coverage: true,
      configuration: "Debug",
      devices: ["iPhone 13 Mini"],
      output_types: "html,junit",
      output_directory: "./fastlane/test_output",
      skip_build: false
    )
  end
end

