# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# devices([
#   "iPhone 13 mini",
#   "iPhone 16 Pro Max",
# ])
#
# languages([
#   "en-US",
#   "ar-SA",
#   "zh-TW",
#   "zh-CN",
#   "fr-FR",
#   "de-DE",
#   "fa-IR",
#   "pa-IN",
#   "pl-PL",
#   "id-ID",
#   "es-ES",
#   "sv-SE",
#   "uk-UA",
#   "ru-RU",
#   "tr-TR",
#   "ja-JP",
#   "ko-KR",
#   "hi-IN",
#   "it-IT",
#   ["pt", "pt_BR"]
# ])

devices([
  "iPhone 13 mini",
  "iPhone 16 Pro Max",
])

languages([
  "en-US",
  "ar-SA"
])

erase_simulator(true)

reinstall_app(true)

# The name of the scheme which contains the UI Tests
scheme("brainwalletUITests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
